settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: default-server
    path: .
    commands:
      install:
        status: true
        method: make build-cli
      run:
        status: true
        method: ./rapid
      fmt:
        status: true
    args:
      - default-http
      - run
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - .realize
        - vendor

  - name: default-grpc-server
    path: .
    commands:
      install:
        status: true
        method: make build-cli
      run:
        status: true
        method: ./rapid
      fmt:
        status: true
    args:
      - default-grpc
      - run
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - .realize
        - vendor

  - name: push-notification-server
    path: .
    commands:
      install:
        status: true
        method: make build-cli
      run:
        status: true
        method: ./rapid
      fmt:
        status: true
    args:
      - push-notification
      - run
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - .realize
        - vendor
